### ISSUE TITLE
my/blocks/issuesを利用する方式を試す

### ISSUE THREAD

**Issue by takenory** [ishikawa999/redmine_vividtone_my_page_blocks#5]

**Comment by ishikawa999** [comment]
issues/list_simple をrenderしている箇所を

my/blocks/issues に、issuesだけでなく、issuesを取得する元となった query をセットする。
現状は Issues.where(...).where(...)としているコードは、IssueQuery#add_filter とするコードに書き換える。

**Comment by ishikawa999** [comment]
基本、下記の太字の部分を書き換えればissuesを利用することができる。

query = IssueQuery.new(:name => l(**:label_block_name**), :user => User.current)
query.add_filter **field, operator, [value1, value2...]**
query.column_names = settings[:columns].presence || **["project","",""]**  # デフォルトでセットするcolumn
query.sort_criteria = settings[:sort].presence || **[["created_at", "asc"]]** # デフォルトでソートしているcolumn, ソート方式 
issues = query.issues(:limit => **10**)  # 表示件数
render :partial => 'my/blocks/issues', :locals => {:query => query, :issues => issues, :block => block}

**Comment by ishikawa999** [comment]
``` rb
issues = Issue.
  .where(["assigned_to_id in (?)", "me"])
  .order(created_on: :desc)
```
上記のようにissuesを検索していた場合は、
my/blocks/issuesを利用するために、以下のような方式に変更する必要がある。
``` rb
query = IssueQuery.new(:name => l(:label_block_name), :user => User.current)
query.add_filter 'assigned_to_id' '=' ["me"]
query.column_names = settings[:columns].presence || ['project', 'tracker', 'status', 'subject']
query.sort_criteria = settings[:sort].presence || [['created_on', 'desc']]
issues = query.issues
```

**Comment by ishikawa999** [comment]
ただ、add_filterでは一つのfieldに対して複数のoparatorを指定すること(OR)はできなさそう。

そのため、neglected_issuesなどでは
```rb
neglected_issues = Issue.visible.open
  .where(["(assigned_to_id in (?) or assigned_to_id is null) and due_date is null and #{Issue.table_name}.updated_on < ?", current_user_ids, Date.today - 7])
```
という条件で絞り込みをしているが、(assigned_to_id in (?) **or** assigned_to_id is null)　など、filterの形に置き換えられない部分がある。

**Comment by takenory** [comment]
Query#issuesメソッドにはoptionが渡せるようになっているので、頑張ればmy/pageには目的の一覧を表示できるようにできるかもしれないです。

例）
```ruby
  issues = query.issues(:order => 'trackers.id',
                        :conditions => "status_id <> #{Tracker.table_name}.default_status_id",
                        :limit => 10)

```

**Comment by ishikawa999** [comment]
```rb
order_option = [group_by_sort_order, (options[:order] || sort_clause)].flatten.reject(&:blank?)
```
IssueQuery#issuesを見ると、
上記のように他のソート条件よりoptionsの方が優先されています。

issuesのoptionに:orderを渡してjoinしようとすると画面上から指定した並び替えが効かなくなるので、それに関しては別の方法を考えた方が良いかもしれません。

**Comment by takenory** [comment]
:includeオプションではどうでしょうか？

例）
```ruby
  issues = query.issues(:include => [:tracker],
                        :conditions => "status_id <> #{Tracker.table_name}.default_status_id",
                        :limit => 10)
```

**Comment by ishikawa999** [comment]
```rb
  issues = query.issues(:include => [:tracker],
                        :conditions => "status_id <> #{Tracker.table_name}.default_status_id",
                        :limit => 10)
```
上の例だと、trackerで並び替えるよう指定された際にエイリアスが重複してしまいエラーとなるため、
```rb
issues = query.issues(  :include => settings[:sort].include?('tracker') ? [] : [:tracker],
                        :conditions => 'issues.status_id <> trackers.default_status_id',
                        :limit => 10)
```
のようにsort条件にtrackerが含まれていない時のみ:include => [:tracker]すれば良さそうです。
